version: '{build}'

skip_tags: true
# AppVeyor automatically skips the build if the commit contains [ci skip] or [skip ci]
#skip_commits:
#  message: /\[ci skip\]/

clone_depth: 10

environment:
  ruby_version: '23'

install:
  - git submodule update --init --recursive
  # Take default Ruby out of path
  - SET PATH=%PATH:C:\Ruby193\bin;=%
  # Add Ruby to path from build matrix
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - node --version
  - gem install bundler --quiet --no-ri --no-rdoc
  - bundler --version
  - bundle
  - choco install phantomjs --version 2.0.0 -y
  
build: off

test_script:
  - bundle exec rake
